import { RedditListingObj, RedditPostObj } from 'src/app/shared/types/reddit.types';

export const MOCK_API_RESPONSE: RedditListingObj<RedditPostObj> = {
  kind: 'Listing',
  data: {
    after: 't3_1i3tn96',
    before: null,
    dist: 10,
    children: [
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_ip0yo',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'TikTok ban rant.',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3ptft',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.85,
          author_flair_background_color: null,
          ups: 8129,
          total_awards_received: 0,
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_480.mp4?source=fallback',
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/s2lfzcwd5mde1/DASHPlaylist.mpd?a=1739778134%2CYjkwZDRhZmY2MGFiYTQwOGI1Zjc1Zjc4NTVkZWU2MDUzNTJmYjRhOTM0NjQyZTg2ZDZiOTVkZjUzMDJjMTg1Ng%3D%3D&amp;v=1&amp;f=sd',
              duration: 84,
              hls_url:
                'https://v.redd.it/s2lfzcwd5mde1/HLSPlaylist.m3u8?a=1739778134%2CMzhlNzc4MGQxYTZmYWI2ZDgzYmU4NGVlZmRhMDRjNDk5ZmRhODJhYzEwMzBjOTA4N2U2YjFiM2E3NTMwMjA5Ng%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Politics',
          can_mod_post: false,
          score: 8129,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=32dc59dd2a66eb85caf7bb0abeee08008ede641a',
          author_flair_css_class: null,
          author_flair_richtext: [],
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737145480,
          link_flair_type: 'text',
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/s2lfzcwd5mde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?format=pjpg&amp;auto=webp&amp;s=4026754ac64fb235e42f6e9e003cb2ae45bdd8da',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=a78a3941b80e0d01cc9e78de7a6238f90de74939',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=79600bc0103db6e3899372aeb98e3441df3387cc',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=9d48754e9c4e9febf664742a9da907dbed1ceb2d',
                    width: 320,
                    height: 568,
                  },
                ],
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#a06324',
          id: '1i3ptft',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'DoJu318',
          discussion_type: null,
          num_comments: 1080,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i3ptft/tiktok_ban_rant/',
          stickied: false,
          url: 'https://v.redd.it/s2lfzcwd5mde1',
          subreddit_subscribers: 4674606,
          created_utc: 1737145480,
          num_crossposts: 7,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_480.mp4?source=fallback',
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/s2lfzcwd5mde1/DASHPlaylist.mpd?a=1739778134%2CYjkwZDRhZmY2MGFiYTQwOGI1Zjc1Zjc4NTVkZWU2MDUzNTJmYjRhOTM0NjQyZTg2ZDZiOTVkZjUzMDJjMTg1Ng%3D%3D&amp;v=1&amp;f=sd',
              duration: 84,
              hls_url:
                'https://v.redd.it/s2lfzcwd5mde1/HLSPlaylist.m3u8?a=1739778134%2CMzhlNzc4MGQxYTZmYWI2ZDgzYmU4NGVlZmRhMDRjNDk5ZmRhODJhYzEwMzBjOTA4N2U2YjFiM2E3NTMwMjA5Ng%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_3qkab',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'I did not have a Roseanne Barr rap song on my 2025 bingo card',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3zu59',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.92,
          author_flair_background_color: null,
          ups: 557,
          total_awards_received: 0,
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/2jbf29rxlode1/DASH_480.mp4?source=fallback',
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/2jbf29rxlode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/2jbf29rxlode1/DASHPlaylist.mpd?a=1739778134%2COWI0OTM4NWI1YmQwNDA0MTU2NjU1MDk5Yjk1NWY2NDg1OTUwYTJmOGZkZGU3YmM4ODNjZTZiYmE2ZjhhYTA4Yw%3D%3D&amp;v=1&amp;f=sd',
              duration: 153,
              hls_url:
                'https://v.redd.it/2jbf29rxlode1/HLSPlaylist.m3u8?a=1739778134%2CZTM2MzUwNjBjYjkwNjg3MTUyOTUxNmFmN2M4N2U0ZTc1MDcxYTAzMzc5ZjJkMDJlM2Q2YWY2ZTBhOThiZjA3Zg%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Cringe',
          can_mod_post: false,
          score: 557,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=81952deeef0d0edb4eea33b13a0ace8cae11b3fc',
          author_flair_css_class: null,
          author_flair_richtext: [],
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737175270,
          link_flair_type: 'text',
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/2jbf29rxlode1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?format=pjpg&amp;auto=webp&amp;s=2f5efe036b6f2fcee2bf9599e2e39c7ddc5a77e9',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=60fdd7b08d00cf422fc55d5f6568c8ca4368343e',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=27931e1f058d7f936da2c3b7758513a9fa650fcb',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=7c66ab67b2839ed7177813d5eb6255625d76d741',
                    width: 320,
                    height: 568,
                  },
                ],
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#ea0027',
          id: '1i3zu59',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'cak3crumbs',
          discussion_type: null,
          num_comments: 124,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i3zu59/i_did_not_have_a_roseanne_barr_rap_song_on_my/',
          stickied: false,
          url: 'https://v.redd.it/2jbf29rxlode1',
          subreddit_subscribers: 4674606,
          created_utc: 1737175270,
          num_crossposts: 0,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/2jbf29rxlode1/DASH_480.mp4?source=fallback',
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/2jbf29rxlode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/2jbf29rxlode1/DASHPlaylist.mpd?a=1739778134%2COWI0OTM4NWI1YmQwNDA0MTU2NjU1MDk5Yjk1NWY2NDg1OTUwYTJmOGZkZGU3YmM4ODNjZTZiYmE2ZjhhYTA4Yw%3D%3D&amp;v=1&amp;f=sd',
              duration: 153,
              hls_url:
                'https://v.redd.it/2jbf29rxlode1/HLSPlaylist.m3u8?a=1739778134%2CZTM2MzUwNjBjYjkwNjg3MTUyOTUxNmFmN2M4N2U0ZTc1MDcxYTAzMzc5ZjJkMDJlM2Q2YWY2ZTBhOThiZjA3Zg%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_elmyrxb6',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'THIS is Why You’re Seeing So Much Chinese Propaganda Here &amp; on TikTok Right Now',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3ybh8',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.76,
          author_flair_background_color: '#ea0027',
          ups: 495,
          total_awards_received: 0,
          thumbnail_width: 140,
          author_flair_template_id: '33e3b16a-53a1-11ea-a3a8-0e8a25d3cbdb',
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/3wynhan76ode1/DASH_480.mp4?source=fallback',
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/3wynhan76ode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/3wynhan76ode1/DASHPlaylist.mpd?a=1739778134%2CODNhZjdlZjU0NzBjOTAwOWQ5Njg1ODVmNGE1ZmU3NGNlODMzY2JiODBlMzkxNzllMDkxYjcwZTlkNmI3ZDZhZQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 170,
              hls_url:
                'https://v.redd.it/3wynhan76ode1/HLSPlaylist.m3u8?a=1739778134%2CODAwZDEwODVjZDY4ODY5YTQ2ODI3ZWNjODk2M2I1YmNjYmQ5MjNkODMwN2VhY2YxN2Y3ZGVhNDEzZmUyZDAxNw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Discussion',
          can_mod_post: false,
          score: 495,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=bc1fcee739ca4984e586d233d26bf4edb5812c92',
          author_flair_css_class: null,
          author_flair_richtext: [],
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737169980,
          link_flair_type: 'text',
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/3wynhan76ode1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?format=pjpg&amp;auto=webp&amp;s=6c5a445f20a6778b917a360e1d6e6518f15a596a',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=9d1234409fd6edb031f35f202e2cd26d03ee2209',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=cf7c3810ac9e3cb20eba453e2e3cc067b771b891',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=e35cce2213d3e75e100453b149b88103a474d0f0',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: 'tHiS iSn’T cRiNgE',
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#0dd3bb',
          id: '1i3ybh8',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'Intelligent_Nose_826',
          discussion_type: null,
          num_comments: 411,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: 'light',
          permalink: '/r/TikTokCringe/comments/1i3ybh8/this_is_why_youre_seeing_so_much_chinese/',
          stickied: false,
          url: 'https://v.redd.it/3wynhan76ode1',
          subreddit_subscribers: 4674606,
          created_utc: 1737169980,
          num_crossposts: 0,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/3wynhan76ode1/DASH_480.mp4?source=fallback',
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/3wynhan76ode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/3wynhan76ode1/DASHPlaylist.mpd?a=1739778134%2CODNhZjdlZjU0NzBjOTAwOWQ5Njg1ODVmNGE1ZmU3NGNlODMzY2JiODBlMzkxNzllMDkxYjcwZTlkNmI3ZDZhZQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 170,
              hls_url:
                'https://v.redd.it/3wynhan76ode1/HLSPlaylist.m3u8?a=1739778134%2CODAwZDEwODVjZDY4ODY5YTQ2ODI3ZWNjODk2M2I1YmNjYmQ5MjNkODMwN2VhY2YxN2Y3ZGVhNDEzZmUyZDAxNw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
    ],
  },
};
