// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { RedditListingObj, RedditPostObj } from 'src/app/shared/types/reddit.types';

export const MOCK_API_RESPONSE: RedditListingObj<RedditPostObj> = {
  kind: 'Listing',
  data: {
    after: 't3_1i42v4n',
    dist: 11,
    modhash: 'b914sxyi29a016f15d0037ea9d82711d00f3413e14796de9f2',
    geo_filter: null,
    children: [
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext:
            '# Use This to Sort by Flair and Find Whatever TikTok Content You\'re Here For!\n\nClick the links below to sort by:\n\n[Cringe](https://www.reddit.com/r/TikTokCringe/search/?q=flair%3Acringe%20-flair%3Ahumor&amp;restrict_sr=1&amp;sort=relevance)\n\n[Humor](https://www.reddit.com/r/TikTokCringe/search/?q=flair%3Ahumor&amp;restrict_sr=1)\n\n[Humor/Cringe](https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Ahumor%2Fcringe&amp;restrict_sr=1)\n\n[Wholesome](https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Awholesome&amp;restrict_sr=1)\n\n[Wholesome/Humor](https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Awholesome%2Fhumor&amp;restrict_sr=1)\n\n[Cool](https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Acool&amp;restrict_sr=1)\n\n[Duet Troll](https://www.reddit.com/r/TikTokCringe/search/?q=flair%3A%22Duet%20Troll%22&amp;restrict_sr=1)\n\n[Cursed](https://www.reddit.com/r/TikTokCringe/search/?q=flair%3Acursed&amp;restrict_sr=1)\n\n[Politics](https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Apolitics&amp;restrict_sr=1)\n\n[Discussion](https://www.reddit.com/r/TikTokCringe/search/?q=flair%3ADiscussion&amp;restrict_sr=1)\n\n(This works best on new reddit and reddit mobile)\n\n**Links for Old Reddit are in the comments**\n\nYou will automatically see posts filtered as the most relevant of all time, so change this as you please.\n\nOf course you can always take a gamble and see all the content on this subreddit at once, but this post is for those looking for a specific type of TikTok.\n\n# FAQ\n\n**"Why is this subreddit called TikTok*****Cringe*** **if there\'s no** ***cringe***?"\n\nThere\'s lots of cringe-worthy content posted here. Click the "Cringe" flair link above and see for yourself. We believe it doesn\'t get upvoted or posted as much as everything else because since the creation of this subreddit, TikTok has really evolved. People are a lot more creative on the app nowadays and don\'t just lip-sync and dance, which is what this subreddit was originally created off of.\n\n"**Why did you start allowing all TikToks? Mods lazy."**\n\nFor why we began allowing TikToks of all kinds, please read [this post](https://www.reddit.com/r/TikTokCringe/comments/fyrgzy/for_those_confused_by_the_name_of_this_subreddit/). It should explain everything.\n\n"**Can I upload my own TikToks here?"**\n\nSure! Be sure when uploading your own content you always use the "OC (I made this)" flair. Not using this flair on your own content will result in a 30 day ban. It may seem like a stupid punishment for something so little, but this helps prevent spam and blatant self advertisement. On top of that, do you really think someone should be able to call their own TikTok "cringe?" Doesn\'t make any sense. Rules like these are what keeps up the quality of this subreddit.\n\n**"How do I post TikToks here?"**\n\nFirst, read all of our rules before posting anything. To post a TikTok here, you must **save** the TikTok in the app, not copy the link. We do not allow links of any kind here. If you would like to share the link to the TikTok you uploaded, feel free to comment it on the post you made, even though this is not required. You can save TikToks by holding down on the video in the app and pressing save. If there\'s no option to save the video, there\'s alternate ways such as clicking the "add to your Instagram story" option which you can then download, or emailing it to yourself. After you save the video, simply create a video post here with the desired TikTok, add a title and flair, and then boom. You\'re done.\n\n"**Why is there an automod comment on every post and who the hell is** [u/BotOrMiss](https://www.reddit.com/u/BotOrMiss/)?"\n\nWe need an automod comment on every post to explain everything you just read. Our subreddit name does not match it\'s content, and it can obviously be very confusing to new users. Some people still miss it somehow, so if you see someone that did, be a good Samaritan and point it out to them. As for [u/BotOrMiss](https://www.reddit.com/u/BotOrMiss/), this is our bot that basically just replaces the automod comment on any post that reaches the top 1000 of [r/all](https://www.reddit.com/r/all/). The bot notifies me because I like to pay attention to and moderate these posts especially. You may also see this bot comment on your post if it was removed because of our removal system we use.\n\nFeel free to ask any further questions you have and we\'d love to hear your suggestions. We\'re always looking for ways to improve our community.\n\nWelp, that\'s it. If you actually read all of this, we appreciate it and owe you a huge thanks. We hope you enjoy your time spent here and get to know our wonderful community.',
          author_fullname: 't2_kus8zf3',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'CLICK HERE TO SORT BY FLAIR! A guide to using r/TikTokCringe',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: null,
          downs: 0,
          thumbnail_height: null,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_kgmu7n',
          quarantine: false,
          link_flair_text_color: 'dark',
          upvote_ratio: 0.99,
          author_flair_background_color: '#ea0027',
          subreddit_type: 'public',
          ups: 2635,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: null,
          author_flair_template_id: '137cf2f2-3a23-11ea-9607-0e110a111823',
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 2635,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: true,
          thumbnail: 'self',
          edited: 1653887356,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          content_categories: null,
          is_self: true,
          mod_note: null,
          created: 1608435563,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'self.TikTokCringe',
          allow_live_comments: true,
          selftext_html:
            '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;h1&gt;Use This to Sort by Flair and Find Whatever TikTok Content You&amp;#39;re Here For!&lt;/h1&gt;\n\n&lt;p&gt;Click the links below to sort by:&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair%3Acringe%20-flair%3Ahumor&amp;amp;restrict_sr=1&amp;amp;sort=relevance"&gt;Cringe&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair%3Ahumor&amp;amp;restrict_sr=1"&gt;Humor&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Ahumor%2Fcringe&amp;amp;restrict_sr=1"&gt;Humor/Cringe&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Awholesome&amp;amp;restrict_sr=1"&gt;Wholesome&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Awholesome%2Fhumor&amp;amp;restrict_sr=1"&gt;Wholesome/Humor&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Acool&amp;amp;restrict_sr=1"&gt;Cool&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair%3A%22Duet%20Troll%22&amp;amp;restrict_sr=1"&gt;Duet Troll&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair%3Acursed&amp;amp;restrict_sr=1"&gt;Cursed&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair_name%3Apolitics&amp;amp;restrict_sr=1"&gt;Politics&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/TikTokCringe/search/?q=flair%3ADiscussion&amp;amp;restrict_sr=1"&gt;Discussion&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;(This works best on new reddit and reddit mobile)&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Links for Old Reddit are in the comments&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;You will automatically see posts filtered as the most relevant of all time, so change this as you please.&lt;/p&gt;\n\n&lt;p&gt;Of course you can always take a gamble and see all the content on this subreddit at once, but this post is for those looking for a specific type of TikTok.&lt;/p&gt;\n\n&lt;h1&gt;FAQ&lt;/h1&gt;\n\n&lt;p&gt;&lt;strong&gt;&amp;quot;Why is this subreddit called TikTok&lt;/strong&gt;&lt;strong&gt;&lt;em&gt;Cringe&lt;/em&gt;&lt;/strong&gt; &lt;strong&gt;if there&amp;#39;s no&lt;/strong&gt; &lt;strong&gt;&lt;em&gt;cringe&lt;/em&gt;&lt;/strong&gt;?&amp;quot;&lt;/p&gt;\n\n&lt;p&gt;There&amp;#39;s lots of cringe-worthy content posted here. Click the &amp;quot;Cringe&amp;quot; flair link above and see for yourself. We believe it doesn&amp;#39;t get upvoted or posted as much as everything else because since the creation of this subreddit, TikTok has really evolved. People are a lot more creative on the app nowadays and don&amp;#39;t just lip-sync and dance, which is what this subreddit was originally created off of.&lt;/p&gt;\n\n&lt;p&gt;&amp;quot;&lt;strong&gt;Why did you start allowing all TikToks? Mods lazy.&amp;quot;&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;For why we began allowing TikToks of all kinds, please read &lt;a href="https://www.reddit.com/r/TikTokCringe/comments/fyrgzy/for_those_confused_by_the_name_of_this_subreddit/"&gt;this post&lt;/a&gt;. It should explain everything.&lt;/p&gt;\n\n&lt;p&gt;&amp;quot;&lt;strong&gt;Can I upload my own TikToks here?&amp;quot;&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;Sure! Be sure when uploading your own content you always use the &amp;quot;OC (I made this)&amp;quot; flair. Not using this flair on your own content will result in a 30 day ban. It may seem like a stupid punishment for something so little, but this helps prevent spam and blatant self advertisement. On top of that, do you really think someone should be able to call their own TikTok &amp;quot;cringe?&amp;quot; Doesn&amp;#39;t make any sense. Rules like these are what keeps up the quality of this subreddit.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;&amp;quot;How do I post TikToks here?&amp;quot;&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;First, read all of our rules before posting anything. To post a TikTok here, you must &lt;strong&gt;save&lt;/strong&gt; the TikTok in the app, not copy the link. We do not allow links of any kind here. If you would like to share the link to the TikTok you uploaded, feel free to comment it on the post you made, even though this is not required. You can save TikToks by holding down on the video in the app and pressing save. If there&amp;#39;s no option to save the video, there&amp;#39;s alternate ways such as clicking the &amp;quot;add to your Instagram story&amp;quot; option which you can then download, or emailing it to yourself. After you save the video, simply create a video post here with the desired TikTok, add a title and flair, and then boom. You&amp;#39;re done.&lt;/p&gt;\n\n&lt;p&gt;&amp;quot;&lt;strong&gt;Why is there an automod comment on every post and who the hell is&lt;/strong&gt; &lt;a href="https://www.reddit.com/u/BotOrMiss/"&gt;u/BotOrMiss&lt;/a&gt;?&amp;quot;&lt;/p&gt;\n\n&lt;p&gt;We need an automod comment on every post to explain everything you just read. Our subreddit name does not match it&amp;#39;s content, and it can obviously be very confusing to new users. Some people still miss it somehow, so if you see someone that did, be a good Samaritan and point it out to them. As for &lt;a href="https://www.reddit.com/u/BotOrMiss/"&gt;u/BotOrMiss&lt;/a&gt;, this is our bot that basically just replaces the automod comment on any post that reaches the top 1000 of &lt;a href="https://www.reddit.com/r/all/"&gt;r/all&lt;/a&gt;. The bot notifies me because I like to pay attention to and moderate these posts especially. You may also see this bot comment on your post if it was removed because of our removal system we use.&lt;/p&gt;\n\n&lt;p&gt;Feel free to ask any further questions you have and we&amp;#39;d love to hear your suggestions. We&amp;#39;re always looking for ways to improve our community.&lt;/p&gt;\n\n&lt;p&gt;Welp, that&amp;#39;s it. If you actually read all of this, we appreciate it and owe you a huge thanks. We hope you enjoy your time spent here and get to know our wonderful community.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          all_awardings: [],
          awarders: [],
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: 'Indian Jokar',
          treatment_tags: [],
          visited: false,
          removed_by: null,
          num_reports: null,
          distinguished: 'moderator',
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: '',
          id: 'kgmu7n',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'Awaake',
          discussion_type: null,
          num_comments: 278,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: 'light',
          permalink: '/r/TikTokCringe/comments/kgmu7n/click_here_to_sort_by_flair_a_guide_to_using/',
          stickied: true,
          url: 'https://www.reddit.com/r/TikTokCringe/comments/kgmu7n/click_here_to_sort_by_flair_a_guide_to_using/',
          subreddit_subscribers: 4674851,
          created_utc: 1608435563,
          num_crossposts: 3,
          media: null,
          is_video: false,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_ip0yo',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'TikTok ban rant.',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3ptft',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.84,
          author_flair_background_color: null,
          ups: 8873,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/s2lfzcwd5mde1/DASHPlaylist.mpd?a=1739784842%2COTI2MmZkZmZmZTdiN2E1ODczNWQ3NzQzMDc0MzM4OWU4Y2Y0N2M2YWMyNjU1ZjA5NjBmMDVlMDYwNzUyZGZlOA%3D%3D&amp;v=1&amp;f=sd',
              duration: 84,
              hls_url:
                'https://v.redd.it/s2lfzcwd5mde1/HLSPlaylist.m3u8?a=1739784842%2CNjcwMzA4YjhiNDVhMzJiMTc1ZDgxZTM4ZjQ2ZDc2MTMzNTllYmFmYmU3NGU0ODkyYzEzYTBhNGE0ZjcyNGMwYQ%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Politics',
          can_mod_post: false,
          score: 8873,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=32dc59dd2a66eb85caf7bb0abeee08008ede641a',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737145480,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/s2lfzcwd5mde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?format=pjpg&amp;auto=webp&amp;s=4026754ac64fb235e42f6e9e003cb2ae45bdd8da',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=a78a3941b80e0d01cc9e78de7a6238f90de74939',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=79600bc0103db6e3899372aeb98e3441df3387cc',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=9d48754e9c4e9febf664742a9da907dbed1ceb2d',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'OXMwODVqdGQ1bWRlMTTCliUcDG6G6wOnhx8TvjXUzEO-iJsLROTMDL7o0jjc',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '3371257e-a670-11ea-96e3-0e21d47e929b',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#a06324',
          id: '1i3ptft',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'DoJu318',
          discussion_type: null,
          num_comments: 1124,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i3ptft/tiktok_ban_rant/',
          stickied: false,
          url: 'https://v.redd.it/s2lfzcwd5mde1',
          subreddit_subscribers: 4674851,
          created_utc: 1737145480,
          num_crossposts: 7,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/s2lfzcwd5mde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/s2lfzcwd5mde1/DASHPlaylist.mpd?a=1739784842%2COTI2MmZkZmZmZTdiN2E1ODczNWQ3NzQzMDc0MzM4OWU4Y2Y0N2M2YWMyNjU1ZjA5NjBmMDVlMDYwNzUyZGZlOA%3D%3D&amp;v=1&amp;f=sd',
              duration: 84,
              hls_url:
                'https://v.redd.it/s2lfzcwd5mde1/HLSPlaylist.m3u8?a=1739784842%2CNjcwMzA4YjhiNDVhMzJiMTc1ZDgxZTM4ZjQ2ZDc2MTMzNTllYmFmYmU3NGU0ODkyYzEzYTBhNGE0ZjcyNGMwYQ%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext:
            'That TMZ “documentary” is bullshit. Compare the documentary and how his friends actually describe m him. The media’s narrative on him is just not rooted in reality. ',
          author_fullname: 't2_da114pqun',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'Media’s spin vs reality on Luigi Mangione ',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 78,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i41uc0',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.98,
          author_flair_background_color: null,
          ups: 981,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/95712xx39pde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 480,
              width: 854,
              scrubber_media_url: 'https://v.redd.it/95712xx39pde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/95712xx39pde1/DASHPlaylist.mpd?a=1739784842%2CNWNlYTE2YTU0ZjU3YjFlNmM4NWEyMWY5Y2FlMDRlZDUzOGQ1YzExNzk5ODU2NjQwM2UyM2IxZDNjMmJhODE2NQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 50,
              hls_url:
                'https://v.redd.it/95712xx39pde1/HLSPlaylist.m3u8?a=1739784842%2CNWYxNGM2ODJkODBjODQ0MzE4Yjg3YzM3Y2Q4YTc4MzZjMDcxMDQ2Yjg1YzUzZDhiMWYyNTc4MzBiNDcyMmE4Mw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Discussion',
          can_mod_post: false,
          score: 981,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm.png?width=140&amp;height=78&amp;crop=140:78,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=01799635d5bfd55031e04e832955e4ed8cad9421',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737183052,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html:
            '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;That TMZ “documentary” is bullshit. Compare the documentary and how his friends actually describe m him. The media’s narrative on him is just not rooted in reality. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/95712xx39pde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm.png?format=pjpg&amp;auto=webp&amp;s=02e4611cd71c85761a8515a306c65655c764280e',
                  width: 1024,
                  height: 576,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=1791e2a24e1b0af7b8f5d64538591ff5005bd9f0',
                    width: 108,
                    height: 60,
                  },
                  {
                    url: 'https://external-preview.redd.it/cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=cec51eda64e2537d1c4ccbd56ea89a55c5f81edc',
                    width: 216,
                    height: 121,
                  },
                  {
                    url: 'https://external-preview.redd.it/cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=24ece7a681bf85f502b47b0205f83543987b8c7c',
                    width: 320,
                    height: 180,
                  },
                  {
                    url: 'https://external-preview.redd.it/cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm.png?width=640&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=3583c6f5f910c847d066ebe7e9e26600ede0b070',
                    width: 640,
                    height: 360,
                  },
                  {
                    url: 'https://external-preview.redd.it/cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm.png?width=960&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=86737e65234af54dcd6db0efd5a0b4ee73568e62',
                    width: 960,
                    height: 540,
                  },
                ],
                variants: {},
                id: 'cTlxZm82czM5cGRlMcIz4YIlHiBEiLkcPFvQB0P6kHQByH8VR2mJjucNkSIm',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '8b725622-f1a8-11e8-9822-0e3a9dfaa784',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#0dd3bb',
          id: '1i41uc0',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'Diligent_Bag4597',
          discussion_type: null,
          num_comments: 83,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i41uc0/medias_spin_vs_reality_on_luigi_mangione/',
          stickied: false,
          url: 'https://v.redd.it/95712xx39pde1',
          subreddit_subscribers: 4674851,
          created_utc: 1737183052,
          num_crossposts: 10,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/95712xx39pde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 480,
              width: 854,
              scrubber_media_url: 'https://v.redd.it/95712xx39pde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/95712xx39pde1/DASHPlaylist.mpd?a=1739784842%2CNWNlYTE2YTU0ZjU3YjFlNmM4NWEyMWY5Y2FlMDRlZDUzOGQ1YzExNzk5ODU2NjQwM2UyM2IxZDNjMmJhODE2NQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 50,
              hls_url:
                'https://v.redd.it/95712xx39pde1/HLSPlaylist.m3u8?a=1739784842%2CNWYxNGM2ODJkODBjODQ0MzE4Yjg3YzM3Y2Q4YTc4MzZjMDcxMDQ2Yjg1YzUzZDhiMWYyNTc4MzBiNDcyMmE4Mw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_3qkab',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'I did not have a Roseanne Barr rap song on my 2025 bingo card',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3zu59',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.92,
          author_flair_background_color: null,
          ups: 786,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/2jbf29rxlode1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/2jbf29rxlode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/2jbf29rxlode1/DASHPlaylist.mpd?a=1739784842%2CMGRmNjNhNjhlNTc3NmVjMmUwM2Q2YWI2M2JhMTEwYzY5YmJjMWZiZGM3NzJhZDg4ZTg0OTYyMjNkMDg1YTg0Yg%3D%3D&amp;v=1&amp;f=sd',
              duration: 153,
              hls_url:
                'https://v.redd.it/2jbf29rxlode1/HLSPlaylist.m3u8?a=1739784842%2CYzhjMjQxNjVhODZhZDdmOGU2MjlkMDExNzIyOTFmZTE1OTZhNWY3MWNkODFiZWU5OGIyNTdmYmFjNmYxMzc1ZA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Cringe',
          can_mod_post: false,
          score: 786,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=81952deeef0d0edb4eea33b13a0ace8cae11b3fc',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737175270,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/2jbf29rxlode1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?format=pjpg&amp;auto=webp&amp;s=2f5efe036b6f2fcee2bf9599e2e39c7ddc5a77e9',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=60fdd7b08d00cf422fc55d5f6568c8ca4368343e',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=27931e1f058d7f936da2c3b7758513a9fa650fcb',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=7c66ab67b2839ed7177813d5eb6255625d76d741',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'MDY4cmlrb3hsb2RlMV5AsVFqwhFHtWb7DUfNRk_RVQKTuUTm5AbqAdZ-0W7A',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: 'd74470ce-5c6c-11e9-9455-0e158690b334',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#ea0027',
          id: '1i3zu59',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'cak3crumbs',
          discussion_type: null,
          num_comments: 181,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i3zu59/i_did_not_have_a_roseanne_barr_rap_song_on_my/',
          stickied: false,
          url: 'https://v.redd.it/2jbf29rxlode1',
          subreddit_subscribers: 4674851,
          created_utc: 1737175270,
          num_crossposts: 0,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/2jbf29rxlode1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/2jbf29rxlode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/2jbf29rxlode1/DASHPlaylist.mpd?a=1739784842%2CMGRmNjNhNjhlNTc3NmVjMmUwM2Q2YWI2M2JhMTEwYzY5YmJjMWZiZGM3NzJhZDg4ZTg0OTYyMjNkMDg1YTg0Yg%3D%3D&amp;v=1&amp;f=sd',
              duration: 153,
              hls_url:
                'https://v.redd.it/2jbf29rxlode1/HLSPlaylist.m3u8?a=1739784842%2CYzhjMjQxNjVhODZhZDdmOGU2MjlkMDExNzIyOTFmZTE1OTZhNWY3MWNkODFiZWU5OGIyNTdmYmFjNmYxMzc1ZA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_u4qv7',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'How to act if you see ICE agents ',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i4041b',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.91,
          author_flair_background_color: null,
          ups: 526,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/eddp2z3yoode1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/eddp2z3yoode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/eddp2z3yoode1/DASHPlaylist.mpd?a=1739784842%2CN2QwNTljZTY3NmRkZjliMTRkZWZkNDAyYjU4MDM3OTI4ZDk0MDMyODAzZDNkZDg5YTNjMmYzYzljOGMwY2Q3Mg%3D%3D&amp;v=1&amp;f=sd',
              duration: 65,
              hls_url:
                'https://v.redd.it/eddp2z3yoode1/HLSPlaylist.m3u8?a=1739784842%2CNTZkZTE1YjQxOTE3YzRiN2Y4NjBlOWU0YjVmZjNjZmQwZTRlMTI5Zjc1OGI4OWU4YzljODhjYTNjNDkyMGY2MA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Discussion',
          can_mod_post: false,
          score: 526,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/MnN3MGlyenhvb2RlMTvQ5wnmsL53X6HeWUaXmQ5naAMofpC-GOSzbgXVVT1L.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=40b09a5c2edb416a6dfedb4cc86e3e9a6eebf6d3',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737176281,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/eddp2z3yoode1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/MnN3MGlyenhvb2RlMTvQ5wnmsL53X6HeWUaXmQ5naAMofpC-GOSzbgXVVT1L.png?format=pjpg&amp;auto=webp&amp;s=9b10cc181a341cea4f3919d6b9081d7197997fff',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/MnN3MGlyenhvb2RlMTvQ5wnmsL53X6HeWUaXmQ5naAMofpC-GOSzbgXVVT1L.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=8a021f51f1c191eb0738f28d5a212b7a65df3ef5',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/MnN3MGlyenhvb2RlMTvQ5wnmsL53X6HeWUaXmQ5naAMofpC-GOSzbgXVVT1L.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=0a794bf5fb2fb7eecf7294f954ad934375d062c5',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/MnN3MGlyenhvb2RlMTvQ5wnmsL53X6HeWUaXmQ5naAMofpC-GOSzbgXVVT1L.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=227b55509d27a776d4a7e397151bcbb513315a72',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'MnN3MGlyenhvb2RlMTvQ5wnmsL53X6HeWUaXmQ5naAMofpC-GOSzbgXVVT1L',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '8b725622-f1a8-11e8-9822-0e3a9dfaa784',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#0dd3bb',
          id: '1i4041b',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'rsmtirish',
          discussion_type: null,
          num_comments: 109,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i4041b/how_to_act_if_you_see_ice_agents/',
          stickied: false,
          url: 'https://v.redd.it/eddp2z3yoode1',
          subreddit_subscribers: 4674851,
          created_utc: 1737176281,
          num_crossposts: 0,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/eddp2z3yoode1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/eddp2z3yoode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/eddp2z3yoode1/DASHPlaylist.mpd?a=1739784842%2CN2QwNTljZTY3NmRkZjliMTRkZWZkNDAyYjU4MDM3OTI4ZDk0MDMyODAzZDNkZDg5YTNjMmYzYzljOGMwY2Q3Mg%3D%3D&amp;v=1&amp;f=sd',
              duration: 65,
              hls_url:
                'https://v.redd.it/eddp2z3yoode1/HLSPlaylist.m3u8?a=1739784842%2CNTZkZTE1YjQxOTE3YzRiN2Y4NjBlOWU0YjVmZjNjZmQwZTRlMTI5Zjc1OGI4OWU4YzljODhjYTNjNDkyMGY2MA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_elmyrxb6',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'THIS is Why You’re Seeing So Much Chinese Propaganda Here &amp; on TikTok Right Now',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3ybh8',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.75,
          author_flair_background_color: '#ea0027',
          ups: 570,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: '33e3b16a-53a1-11ea-a3a8-0e8a25d3cbdb',
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/3wynhan76ode1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/3wynhan76ode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/3wynhan76ode1/DASHPlaylist.mpd?a=1739784842%2CMmRhMGQ1NTc1YjRlYjVjYjBkM2NkOTY4ZjM1ZDliZDMxODk2ZWI4MDQwN2Y2MWMxNGFmYzY0NzJiNzljNjZhYQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 170,
              hls_url:
                'https://v.redd.it/3wynhan76ode1/HLSPlaylist.m3u8?a=1739784842%2COWU0MDEwN2E3NjIxNWU3Nzg4YmIyNzRhMGY5MjZhZWQ5YjMwNjNhYTk1NGEzN2NhMjYxOTBiMmYzYzY4YmY4NA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Discussion',
          can_mod_post: false,
          score: 570,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=bc1fcee739ca4984e586d233d26bf4edb5812c92',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737169980,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/3wynhan76ode1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?format=pjpg&amp;auto=webp&amp;s=6c5a445f20a6778b917a360e1d6e6518f15a596a',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=9d1234409fd6edb031f35f202e2cd26d03ee2209',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=cf7c3810ac9e3cb20eba453e2e3cc067b771b891',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=e35cce2213d3e75e100453b149b88103a474d0f0',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'MHIyNm5sazc2b2RlMcIw0UgqjnlOocgWgDif2iRt-ZJyJUHJm7kpJxyMvyd2',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '8b725622-f1a8-11e8-9822-0e3a9dfaa784',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: 'tHiS iSn’T cRiNgE',
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#0dd3bb',
          id: '1i3ybh8',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'Intelligent_Nose_826',
          discussion_type: null,
          num_comments: 485,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: 'light',
          permalink: '/r/TikTokCringe/comments/1i3ybh8/this_is_why_youre_seeing_so_much_chinese/',
          stickied: false,
          url: 'https://v.redd.it/3wynhan76ode1',
          subreddit_subscribers: 4674851,
          created_utc: 1737169980,
          num_crossposts: 0,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/3wynhan76ode1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/3wynhan76ode1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/3wynhan76ode1/DASHPlaylist.mpd?a=1739784842%2CMmRhMGQ1NTc1YjRlYjVjYjBkM2NkOTY4ZjM1ZDliZDMxODk2ZWI4MDQwN2Y2MWMxNGFmYzY0NzJiNzljNjZhYQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 170,
              hls_url:
                'https://v.redd.it/3wynhan76ode1/HLSPlaylist.m3u8?a=1739784842%2COWU0MDEwN2E3NjIxNWU3Nzg4YmIyNzRhMGY5MjZhZWQ5YjMwNjNhYTk1NGEzN2NhMjYxOTBiMmYzYzY4YmY4NA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext:
            "She captioned it: \n\nI do worry this app may go somewhere or change 😭 and I desperately #tiktok. I have also had some health issues I should be getting to the bottom of tmrw and from there will be playing the stressful health insurance game so in case that doesn't go well or I am distracted I wanted to say this. Per agreement and for leverage I left a few details out and tried to infer where I could. That doesn't mean I won't have more later. I'm going through a difficult time being trapped in maga plus the medical stuff and possibly being fired from TikTok (my only long term ticket out of here) I just want to be honest and warn that what everyone is saying is happening is telling the truth. I want everyone to know that regardless of how hard things get for me I won't sell out. I don't know where I'm going or if I'll get to see you again but if I do, I'll be real. Thank you all so much for giving me the opportunity to existore somewhere. It has been life-saving and therapeutic during a really difficult time in a life that has been difficult to fit in to. I hope l have said enough to infer what I meant to convey. There are Easter eggs in other videos and other much larger creators have been given more. #whistleblower #elonmusk #socialmedia #sellout #urbanlegend #saveriktok #tiktok #rednote #unity #fyp",
          author_fullname: 't2_da114pqun',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title:
            'Whistleblower on why Luigi Mangione and other content may be censored (people paid to post certain content)',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i42af4',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.95,
          author_flair_background_color: null,
          ups: 184,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/izw87ueoepde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/izw87ueoepde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/izw87ueoepde1/DASHPlaylist.mpd?a=1739784842%2CNTY2ZjMwMzY0NTBkMzdjMzE2MzM3ZGEyYTZkYWI2MzMzYTEwZjYzODMyNjFmNjYzOTZhNjdkZmVlOTZmOTI5NQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 266,
              hls_url:
                'https://v.redd.it/izw87ueoepde1/HLSPlaylist.m3u8?a=1739784842%2CNWVhZGM0NTgwNmQ1NjRkYzQxYzY3MTE0Y2JiYTg2YzIxOWI4ZjE4NDM3OTRjMjMyOGY5OTQ2ODUwMDIzNzQwNg%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Discussion',
          can_mod_post: false,
          score: 184,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/amQ2cnp2N29lcGRlMVtwXb7i3a_FAPqDMTcyCbMnDHPCgXwY_Z617crNyn-9.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=590e9fda70f3f2af00c8117f0b947a9490e75ddd',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737184956,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html:
            '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;She captioned it: &lt;/p&gt;\n\n&lt;p&gt;I do worry this app may go somewhere or change 😭 and I desperately #tiktok. I have also had some health issues I should be getting to the bottom of tmrw and from there will be playing the stressful health insurance game so in case that doesn&amp;#39;t go well or I am distracted I wanted to say this. Per agreement and for leverage I left a few details out and tried to infer where I could. That doesn&amp;#39;t mean I won&amp;#39;t have more later. I&amp;#39;m going through a difficult time being trapped in maga plus the medical stuff and possibly being fired from TikTok (my only long term ticket out of here) I just want to be honest and warn that what everyone is saying is happening is telling the truth. I want everyone to know that regardless of how hard things get for me I won&amp;#39;t sell out. I don&amp;#39;t know where I&amp;#39;m going or if I&amp;#39;ll get to see you again but if I do, I&amp;#39;ll be real. Thank you all so much for giving me the opportunity to existore somewhere. It has been life-saving and therapeutic during a really difficult time in a life that has been difficult to fit in to. I hope l have said enough to infer what I meant to convey. There are Easter eggs in other videos and other much larger creators have been given more. #whistleblower #elonmusk #socialmedia #sellout #urbanlegend #saveriktok #tiktok #rednote #unity #fyp&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/izw87ueoepde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/amQ2cnp2N29lcGRlMVtwXb7i3a_FAPqDMTcyCbMnDHPCgXwY_Z617crNyn-9.png?format=pjpg&amp;auto=webp&amp;s=92a4bc70d89669de6680797f5a9b9272bfc46dd1',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/amQ2cnp2N29lcGRlMVtwXb7i3a_FAPqDMTcyCbMnDHPCgXwY_Z617crNyn-9.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=02bf7abf7666d871b13b516f286a75a5747113fc',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/amQ2cnp2N29lcGRlMVtwXb7i3a_FAPqDMTcyCbMnDHPCgXwY_Z617crNyn-9.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=fe5848a043a387ffb657f03bdf2b569519f9ab43',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/amQ2cnp2N29lcGRlMVtwXb7i3a_FAPqDMTcyCbMnDHPCgXwY_Z617crNyn-9.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=bc98943b90bd168a14696ea09534ee34f91184d8',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'amQ2cnp2N29lcGRlMVtwXb7i3a_FAPqDMTcyCbMnDHPCgXwY_Z617crNyn-9',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '8b725622-f1a8-11e8-9822-0e3a9dfaa784',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#0dd3bb',
          id: '1i42af4',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'Diligent_Bag4597',
          discussion_type: null,
          num_comments: 19,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i42af4/whistleblower_on_why_luigi_mangione_and_other/',
          stickied: false,
          url: 'https://v.redd.it/izw87ueoepde1',
          subreddit_subscribers: 4674851,
          created_utc: 1737184956,
          num_crossposts: 13,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/izw87ueoepde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/izw87ueoepde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/izw87ueoepde1/DASHPlaylist.mpd?a=1739784842%2CNTY2ZjMwMzY0NTBkMzdjMzE2MzM3ZGEyYTZkYWI2MzMzYTEwZjYzODMyNjFmNjYzOTZhNjdkZmVlOTZmOTI5NQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 266,
              hls_url:
                'https://v.redd.it/izw87ueoepde1/HLSPlaylist.m3u8?a=1739784842%2CNWVhZGM0NTgwNmQ1NjRkYzQxYzY3MTE0Y2JiYTg2YzIxOWI4ZjE4NDM3OTRjMjMyOGY5OTQ2ODUwMDIzNzQwNg%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_7urq9rsa',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: '"Oligarchy is the new propaganda"',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3qv2c',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.78,
          author_flair_background_color: null,
          ups: 1033,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/6qgzvdnqdmde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/6qgzvdnqdmde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/6qgzvdnqdmde1/DASHPlaylist.mpd?a=1739784842%2CYmRmYWZkNzUzNWY5MmJmNmMzMWE2ZTY4NWYwMDE3MmRiODM5ZDZkODQ2YTcwN2IwMDI5YzFmYmI5NzA2ZGYzNA%3D%3D&amp;v=1&amp;f=sd',
              duration: 112,
              hls_url:
                'https://v.redd.it/6qgzvdnqdmde1/HLSPlaylist.m3u8?a=1739784842%2CZDhkODA1YTA0MTFmODgyNDljYmQ3NmNkMDg3YmJiZGRkMjYzMjAyZjNiZGU3NzJlMWMyNjkwZjA0MzUzNzU3Mg%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Politics',
          can_mod_post: false,
          score: 1033,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/aWZwYW0yaHFkbWRlMeCGluaPXr6g9kZqaqz8StjrlJeFq2jhS-TJa0UJAZkk.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=7cd3dd6762f16c3e041016a8d8084fdabd09e318',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737148289,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/6qgzvdnqdmde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/aWZwYW0yaHFkbWRlMeCGluaPXr6g9kZqaqz8StjrlJeFq2jhS-TJa0UJAZkk.png?format=pjpg&amp;auto=webp&amp;s=6233070f80d2492f4ae56949e51f30f0930128c1',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/aWZwYW0yaHFkbWRlMeCGluaPXr6g9kZqaqz8StjrlJeFq2jhS-TJa0UJAZkk.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=b28398c473936a751c7092a49f518f97b2f6e85d',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/aWZwYW0yaHFkbWRlMeCGluaPXr6g9kZqaqz8StjrlJeFq2jhS-TJa0UJAZkk.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=5de42ec405b14e104e7ec998fa150b17511ee857',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/aWZwYW0yaHFkbWRlMeCGluaPXr6g9kZqaqz8StjrlJeFq2jhS-TJa0UJAZkk.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=6ad81c7e250b69331b996f3064b91eb1d568e6b4',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'aWZwYW0yaHFkbWRlMeCGluaPXr6g9kZqaqz8StjrlJeFq2jhS-TJa0UJAZkk',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '3371257e-a670-11ea-96e3-0e21d47e929b',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#a06324',
          id: '1i3qv2c',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'Naruku_Senpai3861',
          discussion_type: null,
          num_comments: 422,
          send_replies: false,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i3qv2c/oligarchy_is_the_new_propaganda/',
          stickied: false,
          url: 'https://v.redd.it/6qgzvdnqdmde1',
          subreddit_subscribers: 4674851,
          created_utc: 1737148289,
          num_crossposts: 6,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/6qgzvdnqdmde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/6qgzvdnqdmde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/6qgzvdnqdmde1/DASHPlaylist.mpd?a=1739784842%2CYmRmYWZkNzUzNWY5MmJmNmMzMWE2ZTY4NWYwMDE3MmRiODM5ZDZkODQ2YTcwN2IwMDI5YzFmYmI5NzA2ZGYzNA%3D%3D&amp;v=1&amp;f=sd',
              duration: 112,
              hls_url:
                'https://v.redd.it/6qgzvdnqdmde1/HLSPlaylist.m3u8?a=1739784842%2CZDhkODA1YTA0MTFmODgyNDljYmQ3NmNkMDg3YmJiZGRkMjYzMjAyZjNiZGU3NzJlMWMyNjkwZjA0MzUzNzU3Mg%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_kpll5aja',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title:
            "Ben &amp; Jerry's Ice Cream official TikTok account posted a call to action for the People's March happening all over the country tomorrow 1/18/25",
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3uc5n',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.92,
          author_flair_background_color: null,
          ups: 602,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 5000,
              fallback_url: 'https://v.redd.it/s371djqp5nde1/DASH_1080.mp4?source=fallback',
              has_audio: true,
              height: 1920,
              width: 886,
              scrubber_media_url: 'https://v.redd.it/s371djqp5nde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/s371djqp5nde1/DASHPlaylist.mpd?a=1739784842%2CNmUwYjNjODIyZGEyZWU1NGE0YjEwMmYwMDM3YTRkMDhlYzVmNzZjYjM3YTM5YTBmMzQ1MDcwZTI5ZDFkY2MzYw%3D%3D&amp;v=1&amp;f=sd',
              duration: 36,
              hls_url:
                'https://v.redd.it/s371djqp5nde1/HLSPlaylist.m3u8?a=1739784842%2CYTVlOWMwYTg5YTBlNjUwZDU2NzYyZTZlNTZhMjgwZTBjYjU3ZTNhM2I0ODY5OGUwNDVmMmNiMmRmZDI0YWYzMw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Discussion',
          can_mod_post: false,
          score: 602,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=57e6e197424f7898458737837183bb987d4b5f9d',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737157764,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/s371djqp5nde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?format=pjpg&amp;auto=webp&amp;s=4853aafc9ab883597faed0f03e84e682e0410182',
                  width: 1080,
                  height: 2340,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=ccf048ae0ed280ebf01d450bd158e07136bbb689',
                    width: 108,
                    height: 216,
                  },
                  {
                    url: 'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=9cdc9b1d19f22272ea9345753b06656b9ac15c2b',
                    width: 216,
                    height: 432,
                  },
                  {
                    url: 'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=cab4f704f8cca89f28f3fadd816e6a61bec8a3ea',
                    width: 320,
                    height: 640,
                  },
                  {
                    url: 'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?width=640&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=493d68cf8f0be57af02c37bd143e22089a66e12e',
                    width: 640,
                    height: 1280,
                  },
                  {
                    url: 'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?width=960&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=3e5b6b3fc540c2e89fed8366dfe2f1507f314195',
                    width: 960,
                    height: 1920,
                  },
                  {
                    url: 'https://external-preview.redd.it/MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1.png?width=1080&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=6d4e95b0dc2465e312c8f5dc85d36d057ecaaee1',
                    width: 1080,
                    height: 2160,
                  },
                ],
                variants: {},
                id: 'MTYzanZjcnA1bmRlMSUMR1uLkZP951yaRm5e0hxFr2lZUwZqUDB-pVEfsGN1',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '8b725622-f1a8-11e8-9822-0e3a9dfaa784',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#0dd3bb',
          id: '1i3uc5n',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'um_wtfisgoingon',
          discussion_type: null,
          num_comments: 105,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i3uc5n/ben_jerrys_ice_cream_official_tiktok_account/',
          stickied: false,
          url: 'https://v.redd.it/s371djqp5nde1',
          subreddit_subscribers: 4674851,
          created_utc: 1737157764,
          num_crossposts: 2,
          media: {
            reddit_video: {
              bitrate_kbps: 5000,
              fallback_url: 'https://v.redd.it/s371djqp5nde1/DASH_1080.mp4?source=fallback',
              has_audio: true,
              height: 1920,
              width: 886,
              scrubber_media_url: 'https://v.redd.it/s371djqp5nde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/s371djqp5nde1/DASHPlaylist.mpd?a=1739784842%2CNmUwYjNjODIyZGEyZWU1NGE0YjEwMmYwMDM3YTRkMDhlYzVmNzZjYjM3YTM5YTBmMzQ1MDcwZTI5ZDFkY2MzYw%3D%3D&amp;v=1&amp;f=sd',
              duration: 36,
              hls_url:
                'https://v.redd.it/s371djqp5nde1/HLSPlaylist.m3u8?a=1739784842%2CYTVlOWMwYTg5YTBlNjUwZDU2NzYyZTZlNTZhMjgwZTBjYjU3ZTNhM2I0ODY5OGUwNDVmMmNiMmRmZDI0YWYzMw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_3qkab',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: '“Luigi’s game is about to be multiplayer”',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: false,
          name: 't3_1i3f1cy',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.66,
          author_flair_background_color: null,
          ups: 8328,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/tb7ob2pypjde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/tb7ob2pypjde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/tb7ob2pypjde1/DASHPlaylist.mpd?a=1739784842%2COWIzZDRhMjZkYjk0YmQwNDdmYTc2MmVlYzZhMGI1YTk3MGQwY2JkNjUxYTRkNDY3NTc1MGJlZWEwYWExYjIwNQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 319,
              hls_url:
                'https://v.redd.it/tb7ob2pypjde1/HLSPlaylist.m3u8?a=1739784842%2COWM2YWMyNjk4MTE4MTI4Y2UzNmU3OTJhYTVmMjRhODNjYjI1OGU2MGZhN2VjZjIxYmM4Y2VmOGU2ZDBlNzhiOA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Discussion',
          can_mod_post: false,
          score: 8328,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/ZHBkMmVuZ3lwamRlMb0UuJuL3AWArttRpZuV8LaNS7XoYsWZ0Fp_LzBNoTw0.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=a31ac2e84aaab01fa1d1ef9f99b7f29f0f0fe46e',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737116105,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/tb7ob2pypjde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/ZHBkMmVuZ3lwamRlMb0UuJuL3AWArttRpZuV8LaNS7XoYsWZ0Fp_LzBNoTw0.png?format=pjpg&amp;auto=webp&amp;s=a45620c790cd7ce2932f93815572f6f46f00f94b',
                  width: 576,
                  height: 1024,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/ZHBkMmVuZ3lwamRlMb0UuJuL3AWArttRpZuV8LaNS7XoYsWZ0Fp_LzBNoTw0.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=1da9e63170facfbe3bd90f2a8f2cbef4246f77fa',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/ZHBkMmVuZ3lwamRlMb0UuJuL3AWArttRpZuV8LaNS7XoYsWZ0Fp_LzBNoTw0.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=4674e01a62a5b4483d64f2cd60fb257b777fa3c1',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/ZHBkMmVuZ3lwamRlMb0UuJuL3AWArttRpZuV8LaNS7XoYsWZ0Fp_LzBNoTw0.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=59819313de830506c5cb2200e14b5f39d804df90',
                    width: 320,
                    height: 568,
                  },
                ],
                variants: {},
                id: 'ZHBkMmVuZ3lwamRlMb0UuJuL3AWArttRpZuV8LaNS7XoYsWZ0Fp_LzBNoTw0',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '8b725622-f1a8-11e8-9822-0e3a9dfaa784',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#0dd3bb',
          id: '1i3f1cy',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'cak3crumbs',
          discussion_type: null,
          num_comments: 4427,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i3f1cy/luigis_game_is_about_to_be_multiplayer/',
          stickied: false,
          url: 'https://v.redd.it/tb7ob2pypjde1',
          subreddit_subscribers: 4674851,
          created_utc: 1737116105,
          num_crossposts: 22,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/tb7ob2pypjde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/tb7ob2pypjde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/tb7ob2pypjde1/DASHPlaylist.mpd?a=1739784842%2COWIzZDRhMjZkYjk0YmQwNDdmYTc2MmVlYzZhMGI1YTk3MGQwY2JkNjUxYTRkNDY3NTc1MGJlZWEwYWExYjIwNQ%3D%3D&amp;v=1&amp;f=sd',
              duration: 319,
              hls_url:
                'https://v.redd.it/tb7ob2pypjde1/HLSPlaylist.m3u8?a=1739784842%2COWM2YWMyNjk4MTE4MTI4Y2UzNmU3OTJhYTVmMjRhODNjYjI1OGU2MGZhN2VjZjIxYmM4Y2VmOGU2ZDBlNzhiOA%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'TikTokCringe',
          selftext: '',
          author_fullname: 't2_zgab7',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'Absolutely nailed it',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/TikTokCringe',
          hidden: false,
          pwls: null,
          link_flair_css_class: '',
          downs: 0,
          thumbnail_height: 140,
          top_awarded_type: null,
          hide_score: true,
          name: 't3_1i42v4n',
          quarantine: false,
          link_flair_text_color: 'light',
          upvote_ratio: 0.98,
          author_flair_background_color: null,
          ups: 116,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/hrmqnqs6mpde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/hrmqnqs6mpde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/hrmqnqs6mpde1/DASHPlaylist.mpd?a=1739784842%2CMzEwMTM4NmI5OGM5ZGQzYWZhM2ZiOTU5NDhlNTM5NDRjYzRhMThkZTVhMjYyZDNlZDQ3M2M0MzA1ZmJiN2I0NA%3D%3D&amp;v=1&amp;f=sd',
              duration: 86,
              hls_url:
                'https://v.redd.it/hrmqnqs6mpde1/HLSPlaylist.m3u8?a=1739784842%2CMTgwZTY1ZTJhYjM1Njg4MmFiYzlkNjgzMjI2YThmOTcyZDgxNmY4MjU5MWEyZjZhNjE5YzdhZDYzZDU3NWJmYw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Humor',
          can_mod_post: false,
          score: 116,
          approved_by: null,
          is_created_from_ads_ui: false,
          author_premium: false,
          thumbnail:
            'https://external-preview.redd.it/cDgwZXdzczZtcGRlMc1n2R3ln9_93SsAuhkpKhr2-agvKBBljuFO323DzPg9.png?width=140&amp;height=140&amp;crop=140:140,smart&amp;format=jpg&amp;v=enabled&amp;lthumb=true&amp;s=cacd0a867eca71988b786bd240e0a40dd5947709',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'hosted:video',
          content_categories: null,
          is_self: false,
          subreddit_type: 'public',
          created: 1737187487,
          link_flair_type: 'text',
          wls: null,
          removed_by_category: null,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'v.redd.it',
          allow_live_comments: false,
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          url_overridden_by_dest: 'https://v.redd.it/hrmqnqs6mpde1',
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: true,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url: 'https://external-preview.redd.it/cDgwZXdzczZtcGRlMc1n2R3ln9_93SsAuhkpKhr2-agvKBBljuFO323DzPg9.png?format=pjpg&amp;auto=webp&amp;s=93ba1278b487ed6d18357dcefd224cc68e96dbec',
                  width: 480,
                  height: 854,
                },
                resolutions: [
                  {
                    url: 'https://external-preview.redd.it/cDgwZXdzczZtcGRlMc1n2R3ln9_93SsAuhkpKhr2-agvKBBljuFO323DzPg9.png?width=108&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=f9bf5ee8630b2b671a6090b931b134080c87be9d',
                    width: 108,
                    height: 192,
                  },
                  {
                    url: 'https://external-preview.redd.it/cDgwZXdzczZtcGRlMc1n2R3ln9_93SsAuhkpKhr2-agvKBBljuFO323DzPg9.png?width=216&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=015099193ed1ad6d611902ecdfaf35f8c3c58f06',
                    width: 216,
                    height: 384,
                  },
                  {
                    url: 'https://external-preview.redd.it/cDgwZXdzczZtcGRlMc1n2R3ln9_93SsAuhkpKhr2-agvKBBljuFO323DzPg9.png?width=320&amp;crop=smart&amp;format=pjpg&amp;auto=webp&amp;s=a0bb149c4a18cc2e162bbb589858ae1ff5a09fbf',
                    width: 320,
                    height: 569,
                  },
                ],
                variants: {},
                id: 'cDgwZXdzczZtcGRlMc1n2R3ln9_93SsAuhkpKhr2-agvKBBljuFO323DzPg9',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          awarders: [],
          media_only: false,
          link_flair_template_id: '234c4f7c-5c6e-11e9-95b9-0e3466d98bbe',
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          treatment_tags: [],
          visited: false,
          removed_by: null,
          mod_note: null,
          distinguished: null,
          subreddit_id: 't5_mvcq5',
          author_is_blocked: false,
          mod_reason_by: null,
          num_reports: null,
          removal_reason: null,
          link_flair_background_color: '#24a0ed',
          id: '1i42v4n',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'ferry983',
          discussion_type: null,
          num_comments: 14,
          send_replies: true,
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink: '/r/TikTokCringe/comments/1i42v4n/absolutely_nailed_it/',
          stickied: false,
          url: 'https://v.redd.it/hrmqnqs6mpde1',
          subreddit_subscribers: 4674851,
          created_utc: 1737187487,
          num_crossposts: 0,
          media: {
            reddit_video: {
              bitrate_kbps: 1200,
              fallback_url: 'https://v.redd.it/hrmqnqs6mpde1/DASH_480.mp4?source=fallback',
              has_audio: true,
              height: 854,
              width: 480,
              scrubber_media_url: 'https://v.redd.it/hrmqnqs6mpde1/DASH_96.mp4',
              dash_url:
                'https://v.redd.it/hrmqnqs6mpde1/DASHPlaylist.mpd?a=1739784842%2CMzEwMTM4NmI5OGM5ZGQzYWZhM2ZiOTU5NDhlNTM5NDRjYzRhMThkZTVhMjYyZDNlZDQ3M2M0MzA1ZmJiN2I0NA%3D%3D&amp;v=1&amp;f=sd',
              duration: 86,
              hls_url:
                'https://v.redd.it/hrmqnqs6mpde1/HLSPlaylist.m3u8?a=1739784842%2CMTgwZTY1ZTJhYjM1Njg4MmFiYzlkNjgzMjI2YThmOTcyZDgxNmY4MjU5MWEyZjZhNjE5YzdhZDYzZDU3NWJmYw%3D%3D&amp;v=1&amp;f=sd',
              is_gif: false,
              transcoding_status: 'completed',
            },
          },
          is_video: true,
        },
      },
    ],
    before: null,
  },
};
